spring.application.name=MovieTicket

spring.datasource.url=jdbc:postgresql://localhost:5432/movieticket_db
spring.datasource.username=postgres
spring.datasource.password=123456aA@

app.jwt.secret=${JWT_SECRET:-0iNUpxsXh_phv3ZvaDw4m1t0X2IgaMQKlIULSQlM30}
